### ISSUE TITLE
failed to do similarity chat in chroma due to package hnswlib failed to install

### ISSUE THREAD

**Issue by bjwswang** [kubeagi/arcadia#135]
When deploy chromadb in kubebb with charts https://github.com/amikos-tech/chromadb-chart , errors occured in pod logs
```shell
sudo: The "no new privileges" flag is set, which prevents sudo from running as root.
sudo: If sudo is running in a container, you may need to adjust the container configuration to disable the flag.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/chroma-hnswlib/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/chroma-hnswlib/
Collecting chroma-hnswlib
  Obtaining dependency information for chroma-hnswlib from https://files.pythonhosted.org/packages/2f/48/f7609a3cb15a24c5d8ec18911ce10ac94144e9a89584f0a86bf9871b024c/chroma_hnswlib-0.7.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/2f/48/f7609a3cb15a24c5d8ec18911ce10ac94144e9a89584f0a86bf9871b024c/chroma_hnswlib-0.7.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f227178de40>, 'Connection to files.pythonhosted.org timed out. (connect timeout=15)')': /packages/2f/48/f7609a3cb15a24c5d8ec18911ce10ac94144e9a89584f0a86bf9871b024c/chroma_hnswlib-0.7.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/2f/48/f7609a3cb15a24c5d8ec18911ce10ac94144e9a89584f0a86bf9871b024c/chroma_hnswlib-0.7.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/2f/48/f7609a3cb15a24c5d8ec18911ce10ac94144e9a89584f0a86bf9871b024c/chroma_hnswlib-0.7.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/2f/48/f7609a3cb15a24c5d8ec18911ce10ac94144e9a89584f0a86bf9871b024c/chroma_hnswlib-0.7.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Downloading chroma_hnswlib-0.7.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (252 bytes)
INFO: pip is looking at multiple versions of chroma-hnswlib to determine which version is compatible with other requirements. This could take a while.
  Downloading chroma-hnswlib-0.7.2.tar.gz (31 kB)
ERROR: Exception:
Traceback (most recent call last):
  File "/chroma/venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
    yield
  File "/chroma/venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "/chroma/venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "/usr/local/lib/python3.10/http/client.py", line 466, in read
    s = self.fp.read(amt)
  File "/usr/local/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.10/ssl.py", line 1307, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.10/ssl.py", line 1163, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/chroma/venv/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "/chroma/venv/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
    return func(self, options, args)
  File "/chroma/venv/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "/chroma/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
  File "/chroma/venv/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/chroma/venv/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 427, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
  File "/chroma/venv/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 237, in _attempt_to_pin_criterion
    for candidate in criterion.candidates:
  File "/chroma/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/chroma/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "/chroma/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/chroma/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 293, in __init__
    super().__init__(
  File "/chroma/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
    self.dist = self._prepare()
  File "/chroma/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
    dist = self._prepare_distribution()
  File "/chroma/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 304, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/chroma/venv/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 538, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/chroma/venv/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 609, in _prepare_linked_requirement
    local_file = unpack_url(
  File "/chroma/venv/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 166, in unpack_url
    file = get_http_url(
  File "/chroma/venv/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 107, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "/chroma/venv/lib/python3.10/site-packages/pip/_internal/network/download.py", line 147, in __call__
    for chunk in chunks:
  File "/chroma/venv/lib/python3.10/site-packages/pip/_internal/network/utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "/chroma/venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 622, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/chroma/venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 560, in read
    with self._error_catcher():
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/chroma/venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
DEBUG:    [23-10-2023 07:14:37] Starting component System
DEBUG:    [23-10-2023 07:14:37] Starting component Posthog
DEBUG:    [23-10-2023 07:14:37] Starting component SqliteDB
DEBUG:    [23-10-2023 07:14:37] Starting component LocalSegmentManager
DEBUG:    [23-10-2023 07:14:37] Starting component SegmentAPI
INFO:     [23-10-2023 07:14:37] Started server process [13]
INFO:     [23-10-2023 07:14:37] Waiting for application startup.
INFO:     [23-10-2023 07:14:37] Application startup complete.
INFO:     [23-10-2023 07:14:37] Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
```

**Comment by bjwswang** [comment]
> When deploy chromadb in kubebb with charts https://github.com/amikos-tech/chromadb-chart , errors occured in pod logs
> 
> ```shell
> sudo: The "no new privileges" flag is set, which prevents sudo from running as root.
> sudo: If sudo is running in a container, you may need to adjust the container configuration to disable the flag.
> WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/chroma-hnswlib/
> WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/chroma-hnswlib/
> Collecting chroma-hnswlib
>   Obtaining dependency information for chroma-hnswlib from https://files.pythonhosted.org/packages/2f/48/f7609a3cb15a24c5d8ec18911ce10ac94144e9a89584f0a86bf9871b024c/chroma_hnswlib-0.7.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
>   WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/2f/48/f7609a3cb15a24c5d8ec18911ce10ac94144e9a89584f0a86bf9871b024c/chroma_hnswlib-0.7.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
>   WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f227178de40>, 'Connection to files.pythonhosted.org timed out. (connect timeout=15)')': /packages/2f/48/f7609a3cb15a24c5d8ec18911ce10ac94144e9a89584f0a86bf9871b024c/chroma_hnswlib-0.7.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
>   WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/2f/48/f7609a3cb15a24c5d8ec18911ce10ac94144e9a89584f0a86bf9871b024c/chroma_hnswlib-0.7.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
>   WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/2f/48/f7609a3cb15a24c5d8ec18911ce10ac94144e9a89584f0a86bf9871b024c/chroma_hnswlib-0.7.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
>   WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/2f/48/f7609a3cb15a24c5d8ec18911ce10ac94144e9a89584f0a86bf9871b024c/chroma_hnswlib-0.7.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
>   Downloading chroma_hnswlib-0.7.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (252 bytes)
> INFO: pip is looking at multiple versions of chroma-hnswlib to determine which version is compatible with other requirements. This could take a while.
>   Downloading chroma-hnswlib-0.7.2.tar.gz (31 kB)
> ERROR: Exception:
> Traceback (most recent call last):
>   File "/chroma/venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
>     yield
>   File "/chroma/venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 561, in read
>     data = self._fp_read(amt) if not fp_closed else b""
>   File "/chroma/venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 527, in _fp_read
>     return self._fp.read(amt) if amt is not None else self._fp.read()
>   File "/usr/local/lib/python3.10/http/client.py", line 466, in read
>     s = self.fp.read(amt)
>   File "/usr/local/lib/python3.10/socket.py", line 705, in readinto
>     return self._sock.recv_into(b)
>   File "/usr/local/lib/python3.10/ssl.py", line 1307, in recv_into
>     return self.read(nbytes, buffer)
>   File "/usr/local/lib/python3.10/ssl.py", line 1163, in read
>     return self._sslobj.read(len, buffer)
> TimeoutError: The read operation timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/chroma/venv/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
>     status = run_func(*args)
>   File "/chroma/venv/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
>     return func(self, options, args)
>   File "/chroma/venv/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 377, in run
>     requirement_set = resolver.resolve(
>   File "/chroma/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
>     result = self._result = resolver.resolve(
>   File "/chroma/venv/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
>     state = resolution.resolve(requirements, max_rounds=max_rounds)
>   File "/chroma/venv/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 427, in resolve
>     failure_causes = self._attempt_to_pin_criterion(name)
>   File "/chroma/venv/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 237, in _attempt_to_pin_criterion
>     for candidate in criterion.candidates:
>   File "/chroma/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
>     return (c for c in iterator if id(c) not in self._incompatible_ids)
>   File "/chroma/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
>     candidate = func()
>   File "/chroma/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
>     self._link_candidate_cache[link] = LinkCandidate(
>   File "/chroma/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 293, in __init__
>     super().__init__(
>   File "/chroma/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
>     self.dist = self._prepare()
>   File "/chroma/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
>     dist = self._prepare_distribution()
>   File "/chroma/venv/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 304, in _prepare_distribution
>     return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
>   File "/chroma/venv/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 538, in prepare_linked_requirement
>     return self._prepare_linked_requirement(req, parallel_builds)
>   File "/chroma/venv/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 609, in _prepare_linked_requirement
>     local_file = unpack_url(
>   File "/chroma/venv/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 166, in unpack_url
>     file = get_http_url(
>   File "/chroma/venv/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 107, in get_http_url
>     from_path, content_type = download(link, temp_dir.path)
>   File "/chroma/venv/lib/python3.10/site-packages/pip/_internal/network/download.py", line 147, in __call__
>     for chunk in chunks:
>   File "/chroma/venv/lib/python3.10/site-packages/pip/_internal/network/utils.py", line 63, in response_chunks
>     for chunk in response.raw.stream(
>   File "/chroma/venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 622, in stream
>     data = self.read(amt=amt, decode_content=decode_content)
>   File "/chroma/venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 560, in read
>     with self._error_catcher():
>   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
>     self.gen.throw(typ, value, traceback)
>   File "/chroma/venv/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
>     raise ReadTimeoutError(self._pool, None, "Read timed out.")
> pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
> DEBUG:    [23-10-2023 07:14:37] Starting component System
> DEBUG:    [23-10-2023 07:14:37] Starting component Posthog
> DEBUG:    [23-10-2023 07:14:37] Starting component SqliteDB
> DEBUG:    [23-10-2023 07:14:37] Starting component LocalSegmentManager
> DEBUG:    [23-10-2023 07:14:37] Starting component SegmentAPI
> INFO:     [23-10-2023 07:14:37] Started server process [13]
> INFO:     [23-10-2023 07:14:37] Waiting for application startup.
> INFO:     [23-10-2023 07:14:37] Application startup complete.
> INFO:     [23-10-2023 07:14:37] Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
> ```

The `docker-entrypoint.sh` will reinstall `chroma-hnswlib` forcely during pod start.And it failed due to network timeout.

We can install this manully with another index url 

```shell
pip install --force-reinstall --no-cache-dir chroma-hnswlib -i https://mirrors.aliyun.com/pypi/simple/
```
