### ISSUE TITLE
dataprocess pod in example-test failed sometimes

### ISSUE THREAD

**Issue by Abirdcfly** [kubeagi/arcadia#365]
like https://github.com/kubeagi/arcadia/actions/runs/7192102876
```
NAMESPACE            NAME                                                READY   STATUS             RESTARTS        AGE
arcadia              pod/arcadia-apiserver-88c7854b-56v5h                1/1     Running            0               30m
arcadia              pod/arcadia-chromadb-0                              1/1     Running            0               30m
arcadia              pod/arcadia-controller-d8dc76bfc-vks4j              1/1     Running            0               30m
arcadia              pod/arcadia-dataprocess-847886555b-kgz7n            0/1     CrashLoopBackOff   10 (3m7s ago)   30m
arcadia              pod/arcadia-fastchat-6b4b454d69-cqs5g               2/2     Running            0               30m
arcadia              pod/arcadia-minio-57df5cd98c-2b5qq                  1/1     Running            0               30m
arcadia              pod/arcadia-portal-677f6588f4-pvjb7                 1/1     Running            0               30m
kube-system          pod/coredns-57575c5f89-r2w9d                        1/1     Running            0               30m
kube-system          pod/coredns-57575c5f89-xd2n7                        1/1     Running            0               30m
kube-system          pod/etcd-kubeagi-control-plane                      1/1     Running            0               30m
kube-system          pod/kindnet-z2pb9                                   1/1     Running            0               30m
kube-system          pod/kube-apiserver-kubeagi-control-plane            1/1     Running            0               30m
kube-system          pod/kube-controller-manager-kubeagi-control-plane   1/1     Running            0               30m
kube-system          pod/kube-proxy-w95bl                                1/1     Running            0               30m
kube-system          pod/kube-scheduler-kubeagi-control-plane            1/1     Running            0               30m
local-path-storage   pod/local-path-provisioner-c49b7b56f-54dpx          1/1     Running            0               30m
```

pod logs show
```
2023-12-13T08:07:00.668647927Z stderr F Config There is an error when load the config (file path =  config.yml). 
2023-12-13T08:07:00.668681821Z stderr F Traceback (most recent call last):
2023-12-13T08:07:00.668688603Z stderr F   File "/arcadia_app/data_manipulation/common/config.py", line 35, in __init__
2023-12-13T08:07:00.668694024Z stderr F     with open(yaml_file_path, 'r') as file:
2023-12-13T08:07:00.668699955Z stderr F FileNotFoundError: [Errno 2] No such file or directory: 'config.yml'
2023-12-13T08:07:00.668704794Z stderr F 
2023-12-13T08:07:00.668761157Z stderr F Traceback (most recent call last):
2023-12-13T08:07:00.668782207Z stderr F   File "/arcadia_app/data_manipulation/server.py", line 22, in <module>
2023-12-13T08:07:00.668787136Z stderr F     from common.config import config
2023-12-13T08:07:00.668791474Z stderr F   File "/arcadia_app/data_manipulation/common/config.py", line 262, in <module>
2023-12-13T08:07:00.668910752Z stderr F     config = Config()
2023-12-13T08:07:00.668921151Z stderr F   File "/arcadia_app/data_manipulation/utils/class_utils.py", line 28, in __call__
2023-12-13T08:07:00.668990073Z stderr F     cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
2023-12-13T08:07:00.668999721Z stderr F   File "/arcadia_app/data_manipulation/common/config.py", line 49, in __init__
2023-12-13T08:07:00.669062159Z stderr F     self.__set_property_value(yaml_data)
2023-12-13T08:07:00.669067649Z stderr F   File "/arcadia_app/data_manipulation/common/config.py", line 140, in __set_property_value
2023-12-13T08:07:00.669163219Z stderr F     self.open_ai_default_key = self.__get_value_by_key_in_yaml(
2023-12-13T08:07:00.669171294Z stderr F   File "/arcadia_app/data_manipulation/common/config.py", line 246, in __get_value_by_key_in_yaml
2023-12-13T08:07:00.669270836Z stderr F     value = config_json[parent_key].get(key)
2023-12-13T08:07:00.669280334Z stderr F KeyError: 'open_ai'

```

**Comment by wangxinbiao** [comment]
Resolved. Added conditional statements.
`
file = Path(yaml_file_path)
        if not file.exists():
            yaml_file_path=os.path.join(os.getcwd(), 'data_manipulation/config.yml')
`

**Comment by wangxinbiao** [comment]
```shell
file = Path(yaml_file_path)
    if not file.exists(): 
        yaml_file_path=os.path.join(os.getcwd(), 'data_manipulation/config.yml')
```
