### ISSUE TITLE
PDF encryption file processing

### ISSUE THREAD

**Issue by wangxinbiao** [kubeagi/arcadia#761]
An error occurred while processing the encrypted PDF file. Error message:
```
2024-02-26 10:12:17,986 [ERROR] - PDF Handle There is an error when manipulate the text in pdf handler. 
Traceback (most recent call last):
  File "/arcadia_app/src/file_handle/pdf_handle.py", line 84, in handle
    documents = self._get_documents(file_path=file_path)
  File "/arcadia_app/src/file_handle/pdf_handle.py", line 132, in _get_documents
    docs = pdf_loader.load()
  File "/arcadia_app/src/document_loaders/pdf.py", line 56, in load
    documents = pdf_loader.load()
  File "/usr/local/lib/python3.10/site-packages/langchain_community/document_loaders/pdf.py", line 162, in load
    return list(self.lazy_load())
  File "/usr/local/lib/python3.10/site-packages/langchain_community/document_loaders/pdf.py", line 172, in lazy_load
    yield from self.parser.parse(blob)
  File "/usr/local/lib/python3.10/site-packages/langchain_community/document_loaders/base.py", line 111, in parse
    return list(self.lazy_parse(blob))
  File "/usr/local/lib/python3.10/site-packages/langchain_community/document_loaders/parsers/pdf.py", line 95, in lazy_parse
    yield from [
  File "/usr/local/lib/python3.10/site-packages/langchain_community/document_loaders/parsers/pdf.py", line 95, in <listcomp>
    yield from [
  File "/usr/local/lib/python3.10/site-packages/pypdf/_page.py", line 2562, in __iter__
    for i in range(len(self)):
  File "/usr/local/lib/python3.10/site-packages/pypdf/_page.py", line 2493, in __len__
    return self.length_function()
  File "/usr/local/lib/python3.10/site-packages/pypdf/_reader.py", line 459, in _get_num_pages
    return self.trailer[TK.ROOT]["/Pages"]["/Count"]  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/pypdf/generic/_data_structures.py", line 333, in __getitem__
    return dict.__getitem__(self, key).get_object()
  File "/usr/local/lib/python3.10/site-packages/pypdf/generic/_base.py", line 312, in get_object
    obj = self.pdf.get_object(self)
  File "/usr/local/lib/python3.10/site-packages/pypdf/_reader.py", line 1347, in get_object
    retval = self._get_object_from_stream(indirect_reference)  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/pypdf/_reader.py", line 1270, in _get_object_from_stream
    obj_stm: EncodedStreamObject = IndirectObject(stmnum, 0, self).get_object()  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/pypdf/generic/_base.py", line 312, in get_object
    obj = self.pdf.get_object(self)
  File "/usr/local/lib/python3.10/site-packages/pypdf/_reader.py", line 1411, in get_object
    retval = self._encryption.decrypt_object(
  File "/usr/local/lib/python3.10/site-packages/pypdf/_encryption.py", line 850, in decrypt_object
    return cf.decrypt_object(obj)
  File "/usr/local/lib/python3.10/site-packages/pypdf/_encryption.py", line 99, in decrypt_object
    obj._data = self.stm_crypt.decrypt(b_(obj._data))
  File "/usr/local/lib/python3.10/site-packages/pypdf/_crypt_providers/_fallback.py", line 69, in decrypt
    raise DependencyError(_DEPENDENCY_ERROR_STR)
pypdf.errors.DependencyError: cryptography>=3.1 is required for AES algorithm
```

**Comment by bjwswang** [comment]
let's move this to core-library

**Comment by bjwswang** [comment]
should add a library `cryptography`
